=begin
#Invoicetronic API

#The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/

The version of the OpenAPI document: 1
Contact: info@invoicetronic.com
Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Invoicetronic_Sdk
  class DatiGeneraliDocumento < ApiModelBase
    attr_accessor :tipo_documento

    attr_accessor :divisa

    attr_accessor :data

    attr_accessor :numero

    attr_accessor :dati_ritenuta

    attr_accessor :dati_bollo

    attr_accessor :dati_cassa_previdenziale

    attr_accessor :sconto_maggiorazione

    attr_accessor :importo_totale_documento

    attr_accessor :arrotondamento

    attr_accessor :causale

    attr_accessor :art73

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tipo_documento' => :'tipo_documento',
        :'divisa' => :'divisa',
        :'data' => :'data',
        :'numero' => :'numero',
        :'dati_ritenuta' => :'dati_ritenuta',
        :'dati_bollo' => :'dati_bollo',
        :'dati_cassa_previdenziale' => :'dati_cassa_previdenziale',
        :'sconto_maggiorazione' => :'sconto_maggiorazione',
        :'importo_totale_documento' => :'importo_totale_documento',
        :'arrotondamento' => :'arrotondamento',
        :'causale' => :'causale',
        :'art73' => :'art73'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tipo_documento' => :'String',
        :'divisa' => :'String',
        :'data' => :'Time',
        :'numero' => :'String',
        :'dati_ritenuta' => :'Array<DatiRitenuta>',
        :'dati_bollo' => :'DatiBollo',
        :'dati_cassa_previdenziale' => :'Array<DatiCassaPrevidenziale>',
        :'sconto_maggiorazione' => :'Array<ScontoMaggiorazione>',
        :'importo_totale_documento' => :'Float',
        :'arrotondamento' => :'Float',
        :'causale' => :'Array<String>',
        :'art73' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tipo_documento',
        :'divisa',
        :'numero',
        :'dati_ritenuta',
        :'dati_cassa_previdenziale',
        :'sconto_maggiorazione',
        :'importo_totale_documento',
        :'arrotondamento',
        :'causale',
        :'art73'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Invoicetronic_Sdk::DatiGeneraliDocumento` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Invoicetronic_Sdk::DatiGeneraliDocumento`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tipo_documento')
        self.tipo_documento = attributes[:'tipo_documento']
      end

      if attributes.key?(:'divisa')
        self.divisa = attributes[:'divisa']
      end

      if attributes.key?(:'data')
        self.data = attributes[:'data']
      end

      if attributes.key?(:'numero')
        self.numero = attributes[:'numero']
      end

      if attributes.key?(:'dati_ritenuta')
        if (value = attributes[:'dati_ritenuta']).is_a?(Array)
          self.dati_ritenuta = value
        end
      end

      if attributes.key?(:'dati_bollo')
        self.dati_bollo = attributes[:'dati_bollo']
      end

      if attributes.key?(:'dati_cassa_previdenziale')
        if (value = attributes[:'dati_cassa_previdenziale']).is_a?(Array)
          self.dati_cassa_previdenziale = value
        end
      end

      if attributes.key?(:'sconto_maggiorazione')
        if (value = attributes[:'sconto_maggiorazione']).is_a?(Array)
          self.sconto_maggiorazione = value
        end
      end

      if attributes.key?(:'importo_totale_documento')
        self.importo_totale_documento = attributes[:'importo_totale_documento']
      end

      if attributes.key?(:'arrotondamento')
        self.arrotondamento = attributes[:'arrotondamento']
      end

      if attributes.key?(:'causale')
        if (value = attributes[:'causale']).is_a?(Array)
          self.causale = value
        end
      end

      if attributes.key?(:'art73')
        self.art73 = attributes[:'art73']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tipo_documento == o.tipo_documento &&
          divisa == o.divisa &&
          data == o.data &&
          numero == o.numero &&
          dati_ritenuta == o.dati_ritenuta &&
          dati_bollo == o.dati_bollo &&
          dati_cassa_previdenziale == o.dati_cassa_previdenziale &&
          sconto_maggiorazione == o.sconto_maggiorazione &&
          importo_totale_documento == o.importo_totale_documento &&
          arrotondamento == o.arrotondamento &&
          causale == o.causale &&
          art73 == o.art73
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tipo_documento, divisa, data, numero, dati_ritenuta, dati_bollo, dati_cassa_previdenziale, sconto_maggiorazione, importo_totale_documento, arrotondamento, causale, art73].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
