=begin
#Invoicetronic API

#The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/

The version of the OpenAPI document: 1
Contact: support@invoicetronic.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module Invoicetronic_Sdk
  class DatiTrasporto
    attr_accessor :dati_anagrafici_vettore

    attr_accessor :mezzo_trasporto

    attr_accessor :causale_trasporto

    attr_accessor :numero_colli

    attr_accessor :descrizione

    attr_accessor :unita_misura_peso

    attr_accessor :peso_lordo

    attr_accessor :peso_netto

    attr_accessor :data_ora_ritiro

    attr_accessor :data_inizio_trasporto

    attr_accessor :tipo_resa

    attr_accessor :indirizzo_resa

    attr_accessor :data_ora_consegna

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'dati_anagrafici_vettore' => :'dati_anagrafici_vettore',
        :'mezzo_trasporto' => :'mezzo_trasporto',
        :'causale_trasporto' => :'causale_trasporto',
        :'numero_colli' => :'numero_colli',
        :'descrizione' => :'descrizione',
        :'unita_misura_peso' => :'unita_misura_peso',
        :'peso_lordo' => :'peso_lordo',
        :'peso_netto' => :'peso_netto',
        :'data_ora_ritiro' => :'data_ora_ritiro',
        :'data_inizio_trasporto' => :'data_inizio_trasporto',
        :'tipo_resa' => :'tipo_resa',
        :'indirizzo_resa' => :'indirizzo_resa',
        :'data_ora_consegna' => :'data_ora_consegna'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'dati_anagrafici_vettore' => :'DatiAnagraficiVettore',
        :'mezzo_trasporto' => :'String',
        :'causale_trasporto' => :'String',
        :'numero_colli' => :'Integer',
        :'descrizione' => :'String',
        :'unita_misura_peso' => :'String',
        :'peso_lordo' => :'Float',
        :'peso_netto' => :'Float',
        :'data_ora_ritiro' => :'Time',
        :'data_inizio_trasporto' => :'Time',
        :'tipo_resa' => :'String',
        :'indirizzo_resa' => :'IndirizzoResa',
        :'data_ora_consegna' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'mezzo_trasporto',
        :'causale_trasporto',
        :'numero_colli',
        :'descrizione',
        :'unita_misura_peso',
        :'peso_lordo',
        :'peso_netto',
        :'data_ora_ritiro',
        :'data_inizio_trasporto',
        :'tipo_resa',
        :'data_ora_consegna'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Invoicetronic_Sdk::DatiTrasporto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Invoicetronic_Sdk::DatiTrasporto`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'dati_anagrafici_vettore')
        self.dati_anagrafici_vettore = attributes[:'dati_anagrafici_vettore']
      end

      if attributes.key?(:'mezzo_trasporto')
        self.mezzo_trasporto = attributes[:'mezzo_trasporto']
      end

      if attributes.key?(:'causale_trasporto')
        self.causale_trasporto = attributes[:'causale_trasporto']
      end

      if attributes.key?(:'numero_colli')
        self.numero_colli = attributes[:'numero_colli']
      end

      if attributes.key?(:'descrizione')
        self.descrizione = attributes[:'descrizione']
      end

      if attributes.key?(:'unita_misura_peso')
        self.unita_misura_peso = attributes[:'unita_misura_peso']
      end

      if attributes.key?(:'peso_lordo')
        self.peso_lordo = attributes[:'peso_lordo']
      end

      if attributes.key?(:'peso_netto')
        self.peso_netto = attributes[:'peso_netto']
      end

      if attributes.key?(:'data_ora_ritiro')
        self.data_ora_ritiro = attributes[:'data_ora_ritiro']
      end

      if attributes.key?(:'data_inizio_trasporto')
        self.data_inizio_trasporto = attributes[:'data_inizio_trasporto']
      end

      if attributes.key?(:'tipo_resa')
        self.tipo_resa = attributes[:'tipo_resa']
      end

      if attributes.key?(:'indirizzo_resa')
        self.indirizzo_resa = attributes[:'indirizzo_resa']
      end

      if attributes.key?(:'data_ora_consegna')
        self.data_ora_consegna = attributes[:'data_ora_consegna']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          dati_anagrafici_vettore == o.dati_anagrafici_vettore &&
          mezzo_trasporto == o.mezzo_trasporto &&
          causale_trasporto == o.causale_trasporto &&
          numero_colli == o.numero_colli &&
          descrizione == o.descrizione &&
          unita_misura_peso == o.unita_misura_peso &&
          peso_lordo == o.peso_lordo &&
          peso_netto == o.peso_netto &&
          data_ora_ritiro == o.data_ora_ritiro &&
          data_inizio_trasporto == o.data_inizio_trasporto &&
          tipo_resa == o.tipo_resa &&
          indirizzo_resa == o.indirizzo_resa &&
          data_ora_consegna == o.data_ora_consegna
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [dati_anagrafici_vettore, mezzo_trasporto, causale_trasporto, numero_colli, descrizione, unita_misura_peso, peso_lordo, peso_netto, data_ora_ritiro, data_inizio_trasporto, tipo_resa, indirizzo_resa, data_ora_consegna].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Invoicetronic_Sdk.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
