=begin
#Invoicetronic API

#The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/

The version of the OpenAPI document: 1.6.1
Contact: info@invoicetronic.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Invoicetronic_Sdk::ExportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExportApi' do
  before do
    # run before each test
    @api_instance = Invoicetronic_Sdk::ExportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExportApi' do
    it 'should create an instance of ExportApi' do
      expect(@api_instance).to be_instance_of(Invoicetronic_Sdk::ExportApi)
    end
  end

  # unit tests for export_get
  # Export invoices as a ZIP archive
  # Export invoices as a ZIP archive of FatturaPA XML files, suitable for import into accounting software (TeamSystem, Zucchetti, etc.).  **Sent invoices** are only included when they have reached a definitive state (e.g., &#x60;Consegnato&#x60; for private recipients, &#x60;AccettatoDalDestinatario&#x60;, &#x60;DecorrenzaTermini&#x60;, etc.). Invoices still being processed by SDI are excluded.  **Received invoices** are always included. Unread invoices are automatically marked as read and counted as operations.  ### Period filters  You can filter by period using either: - &#x60;year&#x60; + &#x60;month&#x60; (e.g., &#x60;year&#x3D;2026&amp;month&#x3D;3&#x60; for March 2026) - &#x60;year&#x60; + &#x60;quarter&#x60; (e.g., &#x60;year&#x3D;2026&amp;quarter&#x3D;1&#x60; for Q1 Jan-Mar) - &#x60;document_date_from&#x60; / &#x60;document_date_to&#x60; for a custom date range  These options are mutually exclusive. The &#x60;year&#x60; parameter alone is not valid and requires either &#x60;month&#x60; or &#x60;quarter&#x60;.  ### Response  Returns &#x60;200&#x60; with a ZIP archive, or &#x60;204 No Content&#x60; if no invoices match the given filters. Files in the archive are organized by company VAT number (&#x60;{vat}/send/&#x60;, &#x60;{vat}/receive/&#x60;).  ### Rate limiting  This endpoint has a dedicated rate limit: only one export request per user can be processed at a time. Concurrent requests will receive a &#x60;429 Too Many Requests&#x60; response.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :type 
  # @option opts [Integer] :company_id Company id
  # @option opts [Integer] :year 
  # @option opts [Integer] :month 
  # @option opts [Integer] :quarter 
  # @option opts [Time] :document_date_from UTC ISO 8601 (2024-11-29T12:34:56Z)
  # @option opts [Time] :document_date_to UTC ISO 8601 (2024-11-29T12:34:56Z)
  # @return [nil]
  describe 'export_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
