=begin
#Invoicetronic API

#The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/

The version of the OpenAPI document: 1.6.4
Contact: info@invoicetronic.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Invoicetronic_Sdk::HealthApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HealthApi' do
  before do
    # run before each test
    @api_instance = Invoicetronic_Sdk::HealthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HealthApi' do
    it 'should create an instance of HealthApi' do
      expect(@api_instance).to be_instance_of(Invoicetronic_Sdk::HealthApi)
    end
  end

  # unit tests for health_get
  # Health check
  # Returns the health status of the API and its dependencies. No authentication required. Rate limited to 12 requests per minute.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'health_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
