=begin
#Invoicetronic API

#The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/

The version of the OpenAPI document: 1
Contact: info@invoicetronic.com
Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Invoicetronic_Sdk::ReceiveApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReceiveApi' do
  before do
    # run before each test
    @api_instance = Invoicetronic_Sdk::ReceiveApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReceiveApi' do
    it 'should create an instance of ReceiveApi' do
      expect(@api_instance).to be_instance_of(Invoicetronic_Sdk::ReceiveApi)
    end
  end

  # unit tests for receive_get
  # List incoming invoices
  # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :company_id Company id
  # @option opts [String] :identifier SDI identifier.
  # @option opts [Boolean] :unread Unread items only.
  # @option opts [String] :committente Vat number or fiscal code.
  # @option opts [String] :prestatore Vat number or fiscal code.
  # @option opts [String] :file_name File name.
  # @option opts [Time] :last_update_from UTC ISO 8601 (2024-11-29T12:34:56Z)
  # @option opts [Time] :last_update_to UTC ISO 8601 (2024-11-29T12:34:56Z)
  # @option opts [Time] :date_sent_from UTC ISO 8601 (2024-11-29T12:34:56Z)
  # @option opts [Time] :date_sent_to UTC ISO 8601 (2024-11-29T12:34:56Z)
  # @option opts [Time] :document_date_from UTC ISO 8601 (2024-11-29T12:34:56Z)
  # @option opts [Time] :document_date_to UTC ISO 8601 (2024-11-29T12:34:56Z)
  # @option opts [String] :document_number Document number.
  # @option opts [Boolean] :include_payload Include payload in the response. Defaults to false.
  # @option opts [Integer] :page Page number.
  # @option opts [Integer] :page_size Items per page. Cannot be greater than 200.
  # @option opts [String] :sort Sort by field. Prefix with &#39;-&#39; for descending order.
  # @return [Array<Receive>]
  describe 'receive_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for receive_id_delete
  # Delete an incoming invoice by id
  # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
  # @param id Item id
  # @param [Hash] opts the optional parameters
  # @return [Receive]
  describe 'receive_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for receive_id_get
  # Get an incoming invoice by id
  # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
  # @param id Item id
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_payload Include payload in the response. Defaults to false.
  # @return [Receive]
  describe 'receive_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
