=begin
#Italian eInvoice API

#The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. The API also provides advanced features as encryption at rest, invoice validation, multiple upload formats, webhooks, event logging, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/

The version of the OpenAPI document: 1.0.0
Contact: support@invoicetronic.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

# Common files
require 'invoicetronic_invoice_sdk/api_client'
require 'invoicetronic_invoice_sdk/api_error'
require 'invoicetronic_invoice_sdk/version'
require 'invoicetronic_invoice_sdk/configuration'

# Models
require 'invoicetronic_invoice_sdk/models/allegati'
require 'invoicetronic_invoice_sdk/models/altri_dati_gestionali'
require 'invoicetronic_invoice_sdk/models/anagrafica'
require 'invoicetronic_invoice_sdk/models/cedente_prestatore'
require 'invoicetronic_invoice_sdk/models/cessionario_committente'
require 'invoicetronic_invoice_sdk/models/codice_articolo'
require 'invoicetronic_invoice_sdk/models/company'
require 'invoicetronic_invoice_sdk/models/contatti'
require 'invoicetronic_invoice_sdk/models/contatti_trasmittente'
require 'invoicetronic_invoice_sdk/models/dati_anagrafici'
require 'invoicetronic_invoice_sdk/models/dati_anagrafici_cedente_prestatore'
require 'invoicetronic_invoice_sdk/models/dati_anagrafici_cessionario_committente'
require 'invoicetronic_invoice_sdk/models/dati_anagrafici_vettore'
require 'invoicetronic_invoice_sdk/models/dati_beni_servizi'
require 'invoicetronic_invoice_sdk/models/dati_bollo'
require 'invoicetronic_invoice_sdk/models/dati_cassa_previdenziale'
require 'invoicetronic_invoice_sdk/models/dati_contratto'
require 'invoicetronic_invoice_sdk/models/dati_convenzione'
require 'invoicetronic_invoice_sdk/models/dati_ddt'
require 'invoicetronic_invoice_sdk/models/dati_fatture_collegate'
require 'invoicetronic_invoice_sdk/models/dati_generali'
require 'invoicetronic_invoice_sdk/models/dati_generali_documento'
require 'invoicetronic_invoice_sdk/models/dati_ordine_acquisto'
require 'invoicetronic_invoice_sdk/models/dati_pagamento'
require 'invoicetronic_invoice_sdk/models/dati_ricezione'
require 'invoicetronic_invoice_sdk/models/dati_riepilogo'
require 'invoicetronic_invoice_sdk/models/dati_ritenuta'
require 'invoicetronic_invoice_sdk/models/dati_sal'
require 'invoicetronic_invoice_sdk/models/dati_trasmissione'
require 'invoicetronic_invoice_sdk/models/dati_trasporto'
require 'invoicetronic_invoice_sdk/models/dati_veicoli'
require 'invoicetronic_invoice_sdk/models/dettaglio_linee'
require 'invoicetronic_invoice_sdk/models/dettaglio_pagamento'
require 'invoicetronic_invoice_sdk/models/document_data'
require 'invoicetronic_invoice_sdk/models/error'
require 'invoicetronic_invoice_sdk/models/event'
require 'invoicetronic_invoice_sdk/models/fattura_elettronica_body'
require 'invoicetronic_invoice_sdk/models/fattura_elettronica_header'
require 'invoicetronic_invoice_sdk/models/fattura_ordinaria'
require 'invoicetronic_invoice_sdk/models/fattura_principale'
require 'invoicetronic_invoice_sdk/models/id_fiscale_iva'
require 'invoicetronic_invoice_sdk/models/id_trasmittente'
require 'invoicetronic_invoice_sdk/models/indirizzo_resa'
require 'invoicetronic_invoice_sdk/models/iscrizione_rea'
require 'invoicetronic_invoice_sdk/models/model_send'
require 'invoicetronic_invoice_sdk/models/problem_details'
require 'invoicetronic_invoice_sdk/models/problem_http_result'
require 'invoicetronic_invoice_sdk/models/rappresentante_fiscale'
require 'invoicetronic_invoice_sdk/models/rappresentante_fiscale_cessionario_committente'
require 'invoicetronic_invoice_sdk/models/receive'
require 'invoicetronic_invoice_sdk/models/sconto_maggiorazione'
require 'invoicetronic_invoice_sdk/models/sede_cedente_prestatore'
require 'invoicetronic_invoice_sdk/models/sede_cessionario_committente'
require 'invoicetronic_invoice_sdk/models/stabile_organizzazione'
require 'invoicetronic_invoice_sdk/models/terzo_intermediario_o_soggetto_emittente'
require 'invoicetronic_invoice_sdk/models/update'
require 'invoicetronic_invoice_sdk/models/web_hook'
require 'invoicetronic_invoice_sdk/models/web_hook_history'

# APIs
require 'invoicetronic_invoice_sdk/api/company_api'
require 'invoicetronic_invoice_sdk/api/log_api'
require 'invoicetronic_invoice_sdk/api/receive_api'
require 'invoicetronic_invoice_sdk/api/send_api'
require 'invoicetronic_invoice_sdk/api/update_api'
require 'invoicetronic_invoice_sdk/api/webhook_api'

module Invoice_Sdk
  class << self
    # Customize default settings for the SDK using block.
    #   Invoice_Sdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
