=begin
#Invoicetronic API

#The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/

The version of the OpenAPI document: 1
Contact: support@invoicetronic.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'cgi'

module Invoicetronic_Sdk
  class ReceiveApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List incoming invoices
    # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :company_id Company id
    # @option opts [String] :identifier SDI identifier.
    # @option opts [Boolean] :unread Unread items only.
    # @option opts [String] :committente Vat number or fiscal code.
    # @option opts [String] :prestatore Vat number or fiscal code.
    # @option opts [String] :file_name File name.
    # @option opts [Time] :last_update_from UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :last_update_to UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :date_sent_from UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :date_sent_to UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :document_date_from UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :document_date_to UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [String] :document_number Document number.
    # @option opts [Integer] :page Page number. Defaults to 1. (default to 1)
    # @option opts [Integer] :page_size Items per page. Defaults to 50. Cannot be greater than 200. (default to 100)
    # @option opts [String] :sort Sort by field. Prefix with &#39;-&#39; for descending order.
    # @return [Array<Receive>]
    def receive_get(opts = {})
      data, _status_code, _headers = receive_get_with_http_info(opts)
      data
    end

    # List incoming invoices
    # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :company_id Company id
    # @option opts [String] :identifier SDI identifier.
    # @option opts [Boolean] :unread Unread items only.
    # @option opts [String] :committente Vat number or fiscal code.
    # @option opts [String] :prestatore Vat number or fiscal code.
    # @option opts [String] :file_name File name.
    # @option opts [Time] :last_update_from UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :last_update_to UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :date_sent_from UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :date_sent_to UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :document_date_from UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [Time] :document_date_to UTC ISO 8601 (2024-11-29T12:34:56Z)
    # @option opts [String] :document_number Document number.
    # @option opts [Integer] :page Page number. Defaults to 1. (default to 1)
    # @option opts [Integer] :page_size Items per page. Defaults to 50. Cannot be greater than 200. (default to 100)
    # @option opts [String] :sort Sort by field. Prefix with &#39;-&#39; for descending order.
    # @return [Array<(Array<Receive>, Integer, Hash)>] Array<Receive> data, response status code and response headers
    def receive_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ReceiveApi.receive_get ...'
      end
      # resource path
      local_var_path = '/receive'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'company_id'] = opts[:'company_id'] if !opts[:'company_id'].nil?
      query_params[:'identifier'] = opts[:'identifier'] if !opts[:'identifier'].nil?
      query_params[:'unread'] = opts[:'unread'] if !opts[:'unread'].nil?
      query_params[:'committente'] = opts[:'committente'] if !opts[:'committente'].nil?
      query_params[:'prestatore'] = opts[:'prestatore'] if !opts[:'prestatore'].nil?
      query_params[:'file_name'] = opts[:'file_name'] if !opts[:'file_name'].nil?
      query_params[:'last_update_from'] = opts[:'last_update_from'] if !opts[:'last_update_from'].nil?
      query_params[:'last_update_to'] = opts[:'last_update_to'] if !opts[:'last_update_to'].nil?
      query_params[:'date_sent_from'] = opts[:'date_sent_from'] if !opts[:'date_sent_from'].nil?
      query_params[:'date_sent_to'] = opts[:'date_sent_to'] if !opts[:'date_sent_to'].nil?
      query_params[:'document_date_from'] = opts[:'document_date_from'] if !opts[:'document_date_from'].nil?
      query_params[:'document_date_to'] = opts[:'document_date_to'] if !opts[:'document_date_to'].nil?
      query_params[:'document_number'] = opts[:'document_number'] if !opts[:'document_number'].nil?
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'page_size'] = opts[:'page_size'] if !opts[:'page_size'].nil?
      query_params[:'sort'] = opts[:'sort'] if !opts[:'sort'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<Receive>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Basic']

      new_options = opts.merge(
        :operation => :"ReceiveApi.receive_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ReceiveApi#receive_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete an incoming invoice by id
    # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
    # @param id [Integer] Item id
    # @param [Hash] opts the optional parameters
    # @return [Receive]
    def receive_id_delete(id, opts = {})
      data, _status_code, _headers = receive_id_delete_with_http_info(id, opts)
      data
    end

    # Delete an incoming invoice by id
    # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
    # @param id [Integer] Item id
    # @param [Hash] opts the optional parameters
    # @return [Array<(Receive, Integer, Hash)>] Receive data, response status code and response headers
    def receive_id_delete_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ReceiveApi.receive_id_delete ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling ReceiveApi.receive_id_delete"
      end
      # resource path
      local_var_path = '/receive/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Receive'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Basic']

      new_options = opts.merge(
        :operation => :"ReceiveApi.receive_id_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ReceiveApi#receive_id_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get an incoming invoice by id
    # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
    # @param id [Integer] Item id
    # @param [Hash] opts the optional parameters
    # @return [Receive]
    def receive_id_get(id, opts = {})
      data, _status_code, _headers = receive_id_get_with_http_info(id, opts)
      data
    end

    # Get an incoming invoice by id
    # Receive invoices are the invoices that are received from other companies. They are preserved for two years in the live environment and 24 hours in the Sandbox.
    # @param id [Integer] Item id
    # @param [Hash] opts the optional parameters
    # @return [Array<(Receive, Integer, Hash)>] Receive data, response status code and response headers
    def receive_id_get_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ReceiveApi.receive_id_get ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling ReceiveApi.receive_id_get"
      end
      # resource path
      local_var_path = '/receive/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Receive'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Basic']

      new_options = opts.merge(
        :operation => :"ReceiveApi.receive_id_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ReceiveApi#receive_id_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
